/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JadamiluTest */

#ifndef _Included_JadamiluTest
#define _Included_JadamiluTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JadamiluTest
 * Method:    dpjd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JadamiluTest_dpjd
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
